title: 'MommaBearz & DylanBearz Adventure '
description: "Dylan’s introduction into the world of coding and the limitless possibilities of what you can create; for self plus generations coming together to change the world that’s already in half tilt \U0001F680\U0001F5FD\U0001F4BB\U0001F4F2\U0001F4BE⚒⚒\U0001F48E\U0001F48E\U0001F50C\U0001F50C"
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
